### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by ChrislyBear-GH** [cmstead/js-refactor-atom#1] opened 2017-06-17 20:34 UTC
[Enter steps to reproduce:]

1. Install package.
2. Open a .js-file 
3. Highlight a variable to rename
4. Press hotkey (alt-shift-F2)
5. Behold the error.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: CHRISTOPH-W10 - Windows 10 Pro V1607 Build 14393.1358
**Thrown From**: [js-refactor-atom](https://github.com/cmstead/js-refactor-atom) package 0.7.0

### Stack Trace

Uncaught Error: Line 1: Unexpected reserved word

```
At C:\Users\Christoph\.atom\packages\js-refactor-atom\node_modules\esrefactor\node_modules\esprima\esprima.js:3872

Error: Line 1: Unexpected reserved word
    at throwError (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1204:17)
    at parsePrimaryExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1567:16)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at trackLeftHandSideExpressionAllowCall (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3504:61)
    at parsePostfixExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1703:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseUnaryExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1784:16)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseMultiplicativeExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1790:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseAdditiveExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1807:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseShiftExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1824:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseRelationalExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1845:16)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseEqualityExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1863:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseANDExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1880:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseXORExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1896:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseORExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1912:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseLogicalANDExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1930:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseLogicalORExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1946:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseConditionalExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1966:16)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseAssignmentExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:1993:16)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseExpression (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:2020:20)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseStatement (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:2783:16)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at parseSourceElement (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3057:24)
    at parseSourceElements (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3095:29)
    at parseProgram (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3109:19)
    at /packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3609:38
    at Object.parse (/packages/js-refactor-atom/node_modules/esrefactor/node_modules/esprima/esprima.js:3856:23)
    at Context.setCode (/packages/js-refactor-atom/node_modules/esrefactor/lib/esrefactor.js:59:36)
    at /packages/js-refactor-atom/node_modules/esrefactor/lib/esrefactor.js:49:18)
    at renameVar (/packages/js-refactor-atom/lib/modules/refactoring-logic/renameAction.js:16:19)
    at Object.rename (/packages/js-refactor-atom/lib/modules/refactoring-logic/renameAction.js:23:12)
    at /packages/js-refactor-atom/lib/modules/commands/renameFactory.js:18:35
    at /packages/js-refactor-atom/lib/modules/shared/dialogFactory.js:12:7
    at /packages/js-refactor-atom/lib/modules/shared/dialog.js:138:9
    at Array.map (native)
    at Object.onConfirm (/packages/js-refactor-atom/lib/modules/shared/dialog.js:137:32)
    at /packages/js-refactor-atom/lib/modules/shared/dialog.js:76:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  4x -0:50 core:move-left (input.hidden-input)
     -0:49.3.0 intentions:highlight (input.hidden-input)
     -0:49.3.0 core:paste (input.hidden-input)
  4x -0:48.1.0 core:move-right (input.hidden-input)
  9x -0:47.3.0 core:select-right (input.hidden-input)
     -0:46.2.0 core:select-left (input.hidden-input)
     -0:44.9.0 intentions:highlight (input.hidden-input)
     -0:44.6.0 core:save (input.hidden-input)
     -0:43.7.0 intentions:highlight (input.hidden-input)
  2x -0:43.5.0 core:close (input.hidden-input)
     -0:37.9.0 intentions:highlight (input.hidden-input)
     -0:37.1.0 js-refactor-atom:rename (input.hidden-input)
     -0:31.1.0 core:confirm (input.hidden-input)
     -0:13.8.0 intentions:highlight (input.hidden-input)
     -0:13.4.0 js-refactor-atom:rename (input.hidden-input)
     -0:09.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-refactor 0.5.7 
js-refactor-atom 0.7.0 
language-babel 2.66.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.1 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
pigments 0.39.1 
react-snippets 0.8.0 
rest-client 1.3.1 
seti-icons 1.5.4 
seti-ui 1.8.0 
terminal-panel 1.14.1 
```

**Comment by cmstead** [comment] 2017-06-17 21:21
Strange, it was developed on windows 10. I'll give it a look. Thanks for the report.

**Comment by cmstead** [comment] 2017-06-17 21:23
Actually, I'm curious, does the command work when you run it from the menu?

**Comment by ChrislyBear-GH** [comment] 2017-06-17 21:25
I don't know either. Maybe I'm missing some dependencies? Anyway, I reported it because Atom is missing a good and especially >working< refactoring package.

Regarding your second question: 
I tried the hotkey, the menu (via Ctrl-Shift-P), and the right click. Same result every time. Sorry.

**Comment by cmstead** [comment] 2017-06-17 22:02
No, that's really helpful. I just wanted to make sure I had all the info. It the menu option works, but the bit key

**Comment by cmstead** [comment] 2017-06-17 22:04
No, that's really helpful. I just wanted to make sure I had all the info. It the menu option works, but the hot key didn't, that would give me a starting point. If neither work then I can start elsewhere. Thanks for the info! 

Sorry for the multiple posts, the github interface isn't great on a phone.

**Comment by ChrislyBear-GH** [comment] 2017-06-17 22:44
No problem, and thanks for looking into it. Your package looks really promising, so I don't mind some effort.

**Comment by cmstead** [comment] 2017-06-18 02:38
I tried using rename on my Win 10 system and it seems to work as expected.  I'm going to start installing the plugins you listed to see if something breaks because of mixed dependencies or something.

**Comment by cmstead** [comment] 2017-06-18 03:21
I'm not able to replicate the issue with the setup. I was scanning through the error, would it be possible to see the code you were trying to refactor?

Esprima might be choking on something non-standard in your code.  I know Babel will transpile JSX and some other non-standard JS stuff and I've seen Esprima be picky. I might have to investigate a different parser. : /

**Comment by ChrislyBear-GH** [comment] 2017-06-18 10:20
Sure, no problem. Here it is:

```js
import React, {Component} from "react";
import { withRouter, Link, Redirect  } from "react-router-dom";
import { observer, inject } from "mobx-react";
import cn from "classnames";
import Guest from "./Guest";
import Member from "./Member";

import Routes from '../Routes';

import styles from "./index.sass";


@inject("user") @observer
class Application extends Component {
  constructor(props) {
    super(props);
  }

  componentWillMount() {
    this.props.user.signIn();
  }

  guestOrMember() {
    const {user} = this.props;
    if (user.signedIn){
      return(<Member />);
    }

    return(<Guest />);
  }

  render() {

    return (
      <div id="Layout container" className={styles.layout}>
        <div className={cn("pure-menu", "pure-menu-horizontal", "pure-menu-fixed", styles.mainNav)}>
          <Link className={cn("pure-menu-heading", styles.heading)} to="/">Invoiced</Link>
          {this.guestOrMember()}
        </div>
        <Routes />
      </div>
    );
  }
}

export default withRouter(Application);

```

I'm learning React with MobX and this is one of the higher order components. As you can see I'm using ES6 syntax, JSX and some ES2016 decorators.
I was able to refactor a test file just fine with your plugin. This was the test:

```js
function foo() {
  var x = 0,
  x = x + 1;
  console.log(x);
}
foo();
```

Renaming the variable worked. So the problem definitely is the new syntax.

Chris

**Comment by cmstead** [comment] 2017-06-18 19:16
Awesome! Thanks so much. I'll use your example to run tests using Babylon (the Babel parser) and see if I can get everything working with that parser instead of Esprima.

**Comment by cmstead** [comment] 2017-06-19 18:57
Okay, I was able to reproduce the failure in a test using your source. I have a solution which seems to work using Babylon with all the plugins. The one concern which might come to bear is the decorator plugin for babel looks like it is going to be deprecated.  I'll publish the update as soon as I have a chance to pull the release together.

Cheers!

**Comment by cmstead** [comment] 2017-06-19 20:14
I just published version 0.8.0 with a new parser strategy. This issue should be resolved.  Thank you for your help!

**Comment by cmstead** [comment] 2017-06-19 20:17
Correction, v0.9.0 contains the update. v0.8.0 failed to publish.

**Comment by cmstead** [comment] 2017-06-19 20:21
Nope, Esprima was still sneaking around in some of the code. Reopening.

Update: fix is in place for literally EVERYTHING except rename. Rewriting rename to use Babylon, originally was using the esrefactor module.

**Comment by ChrislyBear-GH** [comment] 2017-06-21 09:01
Thanks for your effort! Looking forward to smoothly renaming all my shitty named variables :)

**Comment by cmstead** [comment] 2017-06-23 20:54
Okay, I have a new update.  There is a basic rename behavior in place using Babylon to parse the source.  Everything is working with your example source, so I'm calling this closed for now.  Please see v0.10.1 for the latest update.

Cheers!

**Closed as completed by cmstead** 2017-06-23 20:54 UTC
